In [ ]:
#numpy basic 

In [1]:
#khai báo thư viện numpy
import numpy as np

In [3]:
my_arr = np.arange(100000)

In [4]:
my_list = list(range(100000))

In [6]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 3 ms


In [8]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 721 ms


In [ ]:
#The NumPy ndarray: Mảng đa chiều

In [22]:
#Tạo một số dữ liệu ngẫu nhiên
data = np.random.randn(2, 3)

In [23]:
data

array([[ 1.00006602, -1.0368532 , -1.03586723],
       [-0.30543213,  1.02221555, -0.48552121]])

In [ ]:
#Phép toán với python

In [25]:
data * 10

array([[ 10.00066017, -10.36853205, -10.35867226],
       [ -3.0543213 ,  10.2221555 ,  -4.85521214]])

In [27]:
data + data

array([[ 2.00013203, -2.07370641, -2.07173445],
       [-0.61086426,  2.0444311 , -0.97104243]])

In [28]:
#Hình dạng của dữ liệu
data.shape

(2, 3)

In [29]:
#kiểu của dữ liệu
data.dtype

dtype('float64')

In [ ]:
#tạo ndarray

In [30]:
data1 = [6, 6, 2, 3.2, 0, 1]

In [32]:
arr1 = np.array(data1)
arr1

array([6. , 6. , 2. , 3.2, 0. , 1. ])

In [33]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [34]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
arr2.ndim

2

In [36]:
arr2.shape

(2, 4)

In [37]:
arr1.dtype

dtype('float64')

In [38]:
arr2.dtype

dtype('int32')

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [43]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
#np.empty có thể trả về giá trị rác chưa được khởi tạo

In [1]:
import pandas as pd 
y_tbl = pd.read_csv("./data/test.csv")
y_tbl