In [3]:
#numpy basic 

In [4]:
#khai báo thư viện numpy
import numpy as np

In [5]:
my_arr = np.arange(100000)

In [6]:
my_list = list(range(100000))

In [7]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 2 ms


In [8]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 249 ms


In [9]:
#The NumPy ndarray: Mảng đa chiều

In [10]:
#Tạo một số dữ liệu ngẫu nhiên
data = np.random.randn(2, 3)

In [11]:
data

array([[ 1.71345478, -0.24265397, -1.65811581],
       [ 0.70874046, -0.40531548, -1.8146769 ]])

In [12]:
#Phép toán với python

In [13]:
data * 10

array([[ 17.13454782,  -2.42653965, -16.58115815],
       [  7.08740459,  -4.05315484, -18.14676904]])

In [14]:
data + data

array([[ 3.42690956, -0.48530793, -3.31623163],
       [ 1.41748092, -0.81063097, -3.62935381]])

In [15]:
#Hình dạng của dữ liệu
data.shape

(2, 3)

In [16]:
#kiểu của dữ liệu
data.dtype

dtype('float64')

In [17]:
#tạo ndarray

In [18]:
data1 = [6, 6, 2, 3.2, 0, 1]

In [19]:
arr1 = np.array(data1)
arr1

array([6. , 6. , 2. , 3.2, 0. , 1. ])

In [20]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [21]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr2.ndim

2

In [23]:
arr2.shape

(2, 4)

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int32')

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
np.empty((2, 3, 2))

array([[[1.40067606e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.58817677e-052]],

       [[5.59007241e-091, 2.82981745e-056],
        [2.36620153e+179, 3.11422360e-032],
        [3.99910963e+252, 4.93432906e+257]]])

In [29]:
#np.empty có thể trả về giá trị rác chưa được khởi tạo

In [30]:
import pandas as pd 
y_tbl = pd.read_csv("./data/test.csv")
y_tbl

Function                                        Description
0              array  Convert input data (list, tuple, array, or oth...
1            asarray  Convert input to ndarray, but do not copy if t...
2             arange  Like the built-in range but returns an ndarray...
3    ones, ones_like  Produce an array of all 1s with the given shap...
4  zeros, zeros_like  Like ones and ones_like but producing arrays o...
5  empty, empty_like  Create new arrays by allocating new memory, bu...
6    full, full_like  Produce an array of the given shape and dtype ...
7      eye, identity  Create a square N × N identity matrix (1s on t...

kiểu dữ liệu trong ndarrays

In [31]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [32]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [33]:
arr1.dtype

dtype('float64')

In [34]:
arr2.dtype

dtype('int32')

In [35]:
dtype_tbl = pd.read_csv("./data/Numpy_data_types.csv")
dtype_tbl

Type  Type code  \
0    int16, uint16    i2, u2    
1   int32, uint32      i4, u4   
2   int64, uint64      i8, u8   
3      int8, uint8     i1, u1   
4          float16         f2   
5          float32    f4 or f   
6          float64    f8 or d   
7         float128   f16 or g   
8        complex64         c8   
9       complex128        c16   
10      complex256        c32   
11            bool          ?   
12          object          O   
13         string_          S   
14        unicode_          U   

                                          Description  
0      Các kiểu số nguyên 16 bit có dấu và không dấu   
1       Các kiểu số nguyên 32bit có dấu và không dấu   
2       Các kiểu số nguyên 64bit có dấu và không dấu   
3   Các kiểu số nguyên 8 bit (1 byte) có dấu và kh...  
4                         Dấu chấm động nửa chính xác  
5   Dấu phẩy động chính xác đơn tiêu chuẩn; tương ...  
6   Dấu phẩy động chính xác kép tiêu chuẩn; tương ...  
7                     Dấu chấm động chính xác mở rộng  
8   Các số phức được biểu thị bằng hai số nổi 32, ...  
9                                                 NaN  
10                                                NaN  
11       Kiểu boolean lưu trữ các giá trị Đúng và Sai  
12  Kiểu đối tượng Python; một giá trị có thể là b...  
13  Kiểu chuỗi ASCII có độ dài cố định (1 byte cho...  
14  Loại Unicode có độ dài cố định (số byte dành r...

In [36]:
df = pd.DataFrame(dtype_tbl)

# chọn dòng theo label
d = df.loc[12][2]

print(d)

Kiểu đối tượng Python; một giá trị có thể là bất kỳ đối tượng Python nào


chuyển đổi kiểu dữ liệu

In [37]:
arr = np.array([1, 2, 3, 4, 5])

In [38]:
arr.dtype

dtype('int32')

In [39]:
float_arr = arr.astype(np.float64)

In [40]:
float_arr.dtype

dtype('float64')

đổi floating sang int

In [41]:
arr = np.array([3.123, -1,2, 4.5, -2.3, 1.00])

In [42]:
arr

array([ 3.123, -1.   ,  2.   ,  4.5  , -2.3  ,  1.   ])

In [43]:
d = arr.astype(np.int32)

In [44]:
d

array([ 3, -1,  2,  4, -2,  1])

bạn có thế sử dụng thuộc tính dtype của mảng này cho mảng khác

In [47]:
int_array = np.arange(10)

In [48]:
calibers = np.array([.22, .270, .357, .380, .44], dtype=np.float64)

In [50]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Việc gọi astype luôn tạo ra một mảng mới (bản sao của dữ liệu), ngay cả khi kiểu mới giống với kiểu cũ.


Số học với Numpy Array

In [51]:
arr = np.array([[1. ,2. ,3. ], [4. ,5. ,6. ]])

In [52]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [53]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [54]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Các phép toán số học với vô hướng truyền đối số vô hướng đến từng phần tử trong mảng

In [55]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [56]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

So sánh giữa các mảng có cùng kích thước mang lại các mảng boolean:

In [59]:
arr2 = np.array([[1. , 3., 9.],[2. , 4. , 8.]])

In [60]:
arr2 > arr

array([[False,  True,  True],
       [False, False,  True]])